config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'activities#index'
  resources :activities, only: %i[index show create download_zip download_pdf] do
    member do
      get :download_zip
      get :download_pdf
    end
  end
end

app/models/activity.rb
# frozen_string_literal: true

require 'uri'
require 'prawn'
require 'zip'
require 'digest'
require 'redis/objects'

class ValidateUrlError < StandardError
end

class RecordNotFound < StandardError
end

class ContributorNotFound < StandardError
end

class ResponseIsEmpty < StandardError
end

# class representing the layer between the application and the api github
class Activity
  include HTTParty
  include Redis::Objects
  attr_reader :url
  attr_reader :data
  attr_reader :id
  attr_reader :files

  NUMBER_OF_CONTRIBUTORS = 3
  MAX_RETRIES = 3

  def initialize(params)
    url = params[:url]
    @url = url
    @id = "activity:#{Digest::MD5.hexdigest url}"
    @data = params[:data]
    @files = {
      diploma: "public/diploma_#{@id}",
      archive: "public/archive_#{@id}.zip"
    }
  end

  def save
    redis.set(@id, Marshal.dump(self))
  end

  def self.cache_public_contributors(url)
    Rails.cache.fetch([url, __method__], expires_in: 30.minutes) do
      public_contributors(url)
    end
  end

  def self.public_contributors(url)
    validate_url(url)
    param = parse(url)
    api_url = "https://api.github.com/repos/#{param}/stats/contributors"
    select_contributors(try_take_contributors(api_url))
  end

  def self.try_take_contributors(api_url)
    response = HTTParty.get(api_url)
    raise ResponseIsEmpty, 'data is empty' if response.parsed_response.empty?

    response.parsed_response
  rescue ResponseIsEmpty => error
    @retries ||= 0
    raise error if @retries > MAX_RETRIES

    @retries += 1
    retry
  end

  def self.validate_url(url)
    unless url.match?(URI::DEFAULT_PARSER.make_regexp)
      raise ValidateUrlError, 'its not url'
    end
    raise ValidateUrlError, 'only github' unless url.include? 'github.com'
  end

  def self.parse(str)
    str.split('/').last(2).join('/')
  end

  def self.select_contributors(contributors)
    list_of = contributors.last(NUMBER_OF_CONTRIBUTORS)
    list_of.each do |contributor|
      contributor.delete('weeks')
    end
    list_of.reverse
  end

  def diploma(top)
    raise ContributorNotFound, 'contributor not found' unless data[top]

    name = data.dig(top, 'author', 'login')
    file_name = "#{@files[:diploma]}_#{name}.pdf"

    return file_name if File.exist? file_name

    total = data.dig(top, 'total')
    generate_pdf(name, total, top, file_name)
  end

  def create_zip
    zipfile_name = @files[:archive]
    return zipfile_name if File.exist? zipfile_name

    Zip::File.open(zipfile_name, Zip::File::CREATE) do |zipfile|
      (0...NUMBER_OF_CONTRIBUTORS).each do |index|
        file_name = diploma(index)
        zipfile.add(file_name, File.join('./', file_name))
      end
    end
    zipfile_name
  end

  def self.find(id)
    result = redis.get id
    raise RecordNotFound, 'Sorry, record does not exist' unless result

    Marshal.load result
  end

  def self.all
    redis.keys('activity:*').collect { |key| find(key) }
  end

  private

  def generate_pdf(name, total, top, file_name)
    pdf = Prawn::Document.new
    pdf.move_down 50
    pdf.text("##{top + 1}", align: :center, size: 72)
    pdf.text(name.to_s, align: :center, size: 44)
    pdf.text(total.to_s, align: :center, size: 14)
    pdf.render_file file_name
    file_name
  end
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

# controller processes all requests related to the activity
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[show download_zip download_pdf]

  def index
    @activities = Activity.all
  end

  def show
    @url = @activity.url
    @show = @activity.data
  end

  def create
    url = activity_params[:url]
    data = Activity.cache_public_contributors(url)
    @activity = Activity.new(url: url, data: data)
    @activity.save
    redirect_to activity_path(id: @activity.id)
  rescue StandardError => e
    redirect_to root_path, alert: e.message
  end

  def download_zip
    name = @activity.create_zip
    send_file name, disposition: 'attachment'
  rescue Errno::ENOENT
    redirect_to root_path, alert: 'zip not found'
  rescue ContributorNotFound => error
    redirect_to root_path, alert: error.message
  end

  def download_pdf
    name = @activity.diploma(params[:top].to_i)
    send_file name, disposition: 'attachment'
  rescue Errno::ENOENT
    redirect_to root_path, alert: 'pdf not found'
  rescue ContributorNotFound => error
    redirect_to root_path, alert: error.message
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  rescue RecordNotFound => error
    redirect_to root_path, alert: error.message
  end

  def activity_params
    params.require(:activity).permit(:url)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# default controller
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# default app helper
module ApplicationHelper
end

app/views/activities/index.html.erb
<%= render 'search' %>
<div class="h4">History</div>

<ul class="list-group">
  <% @activities.each do |activity| %>
    <%= link_to activity.url.to_s, activity_path(id: activity.id), class: 'list-group-item list-group-item-action' %>
  <% end %>
</ul>

app/views/activities/show.html.erb
<%= render 'search' %>
<section class="jumbotron text-center" style="padding: 1rem 1rem;">
  <div class="container">
    <h1 class="jumbotron-heading">Top <%= pluralize(@show.count, 'contributor') %></h1>
    <p class="lead text-muted"><%= link_to @url, @url %></p>
    <p>
      <%= link_to 'Download result', download_zip_activity_path, class: 'btn btn-outline-primary' %>
    </p>
  </div>
</section>

<div class="card-group">
  <% @show.each_with_index do |user, index| %>
    <%= render 'user', {user: user, top: index} %>
  <% end %>
</div>

app/views/application/_notice.html.erb
<div class="alert alert-<%= type %> alert-dismissible fade show" role="alert">
  <%= text %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/application/_notices.html.erb
<% if notice %>
  <%= render partial: "notice", locals: {text: notice, type: 'success'} %>
<% elsif alert %>
  <%= render partial: "notice", locals: {text: alert, type: 'danger'} %>
<% end %>

app/views/application/_search.html.erb
<%= form_for :activity, url: activities_path do |f| %>
  <div class="align-middle input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">GitHub repo path</span>
    </div>
    <%= f.text_field :url, class: 'form-control', placeholder: 'https://github.com/rails/rails' %>
    <div class="input-group-append">
      <%= f.submit class: "btn btn-outline-success", value: 'search' %>
    </div>
  </div>
<% end %>

app/views/application/_user.html.erb
<div class="card">
  <img class="card-img-top" src="<%= user["author"]["avatar_url"] %>" alt="<%= user["author"]["login"] %>">
  <div class="card-body">
    <small class="text-muted float-sm-right">
      <%= link_to 'Download PDF', download_pdf_activity_path(top: top), class: "text-right text-muted" %>
    </small>
    <%= link_to user["author"]["login"], user["author"]["html_url"], class: "card-title" %>
    <p class="card-text"><%= user["total"] %> commits</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TryUchiRu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <%= render partial: "notices" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>